<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.2</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.integration.library.librarysystem</groupId>
	<artifactId>libraryintegrationsystem</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<name>LibraryIntegrationSystem</name>
	<description>Demo project for Library backend System with Spring Boot</description>
	<properties>
		<java.version>17</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.modelmapper/modelmapper -->
		<dependency>
			<groupId>org.modelmapper</groupId>
			<artifactId>modelmapper</artifactId>
			<version>LATEST</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.openapitools</groupId>
			<artifactId>jackson-databind-nullable</artifactId>
			<version>0.2.6</version> <!-- Use latest if needed -->
		</dependency>
		<dependency>
			<groupId>jakarta.validation</groupId>
			<artifactId>jakarta.validation-api</artifactId>
			<version>3.0.2</version> <!-- You can choose the latest version -->
		</dependency>
		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-annotations</artifactId>
			<version>2.2.30</version> <!-- Use the latest available version -->
		</dependency>

		<!--<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-mongodb</artifactId>
		</dependency>

		&lt;!&ndash; https://mvnrepository.com/artifact/org.springframework.data/spring-data-mongodb &ndash;&gt;
		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-mongodb</artifactId>
		</dependency>-->

		<!-- https://mvnrepository.com/artifact/org.mongodb/mongodb-driver-sync -->
		<!--<dependency>
			<groupId>org.mongodb</groupId>
			<artifactId>mongodb-driver-sync</artifactId>
		</dependency>-->
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<version>7.12.0</version>
				<executions>
					<execution>
						<id>libraryviewsystem</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${project.basedir}/src/main/java/com/integration/library/librarysystem/libraryintegrationsystem/api/libraryintegrationsystem-contract.yaml
							</inputSpec>
							<generatorName>spring</generatorName>
							<apiPackage>com.integration.library.librarysystem.libraryintegrationsystem.api</apiPackage>
							<generateApis>false</generateApis>
							<generateModels>true</generateModels>
							<modelPackage>com.integration.library.librarysystem.libraryviewsystem.models.api</modelPackage>
							<invokerPackage>com.integration.library.librarysystem.libraryviewsystem.adapter</invokerPackage>
							<output>${project.build.directory}/generated-sources</output>
							<addCompileSourceRoot>true</addCompileSourceRoot>
							<configOptions>
								<dateLibrary>java8-localdatetime</dateLibrary>
								<sourceFolder>openapi</sourceFolder>
								<!-- delegatePattern can be used to generate a delegate class that could be implemented/extended to simplify implementation -->
								<delegatePattern>false</delegatePattern>
							</configOptions>
							<!--<importMappings>
								&lt;!&ndash; Use the generic classes instead of the ones generated in the API (if possible) &ndash;&gt;
								<importMapping>SError=se.lf.csp.common.serviceapi.api.SError</importMapping>
								<importMapping>SResponse=se.lf.csp.common.serviceapi.api.SResponse</importMapping>
							</importMappings>-->
							<!-- disable generation of files not needed -->
							<generateSupportingFiles>false</generateSupportingFiles>
							<generateModelDocumentation>false</generateModelDocumentation>
							<generateApiDocumentation>false</generateApiDocumentation>
							<generateApiTests>false</generateApiTests>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.google.code.maven-replacer-plugin</groupId>
				<artifactId>replacer</artifactId>
				<version>1.5.3</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>replace</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<includes>
						<include>${project.build.directory}/generated-sources/**/*.java</include>
					</includes>
					<regex>false</regex>
					<replacements>
						<replacement>
							<token>javax.validation</token>
							<value>jakarta.validation</value>
						</replacement>
						<replacement>
							<token>javax.annotation</token>
							<value>jakarta.annotation</value>
						</replacement>
					</replacements>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
